name: waline

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
  push:
    paths:
    - 'waline/**'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Log into registry ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/love4taylor/waline
          labels: |
            org.opencontainers.image.title=waline
            org.opencontainers.image.authors=love4taylor
            org.opencontainers.image.description=Support services in containers on the same network to be able to access Waline by adding a line host:'0.0.0.0' to the official code.
            org.opencontainers.image.url=https://github.com/love4taylor/dockerfile/tree/master/waline
            org.opencontainers.image.source=https://github.com/walinejs/waline
            org.opencontainers.image.version=1.7.0

      # Necessary for Multi-Arch images
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # Get buildx ready
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./waline/
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ghcr.io/love4taylor/waline:latest
          labels: ${{ steps.meta.outputs.labels }}
